name: web_template
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  matrix4_transform: ^2.0.1
  get: ^4.6.5
  photo_view: ^0.14.0
  painter: ^2.0.0
  flutter_boxicons: ^3.0.0
  o_color_picker: ^1.0.2
  go_router: ^5.1.1
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:

  assets:
    - assets/
  uses-material-design: true
